#:schema https://www.schemastore.org/cargo.json

[package]
name = "test262"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
oxc = { workspace = true, features = ["codegen", "semantic"] }
oxc_estree_codec = { workspace = true }
test_helpers = { workspace = true }
